INSERT INTO sys_permission_config(PERMISSION_CONFIG_ID, PERMISSION_URL, PERMISSION_CONFIG, SEQ_NO, REMARK, PERMISSION_NAME, ICON, PERMISSION_TYPE, P_PERMISSION_ID, SYS_ID, SORT_NO, DISPLAY, ALIVE_FLAG, ADD_USER_ID, ADD_TIME, OPR_USER_ID, OPR_TIME, SUBSYS_CODE, CHECK_FLAG) VALUES(1, '', 'sys:user:list', NULL, '权限管理', '权限管理', NULL, False, 0, NULL, 1, 1, NULL, 1, '2018-05-06 23:31:00', 1, '2018-05-06 23:31:18', 'MENU_USER', NULL);
INSERT INTO sys_permission_config(PERMISSION_CONFIG_ID, PERMISSION_URL, PERMISSION_CONFIG, SEQ_NO, REMARK, PERMISSION_NAME, ICON, PERMISSION_TYPE, P_PERMISSION_ID, SYS_ID, SORT_NO, DISPLAY, ALIVE_FLAG, ADD_USER_ID, ADD_TIME, OPR_USER_ID, OPR_TIME, SUBSYS_CODE, CHECK_FLAG) VALUES(2, 'admin/menu/menuList', 'sys:user:list', NULL, '菜单管理', '菜单管理', NULL, True, 1, NULL, 1, 1, NULL, 1, '2018-05-06 23:32:23', 1, '2018-05-06 23:32:38', 'MENU_USER', NULL);
INSERT INTO sys_permission_config(PERMISSION_CONFIG_ID, PERMISSION_URL, PERMISSION_CONFIG, SEQ_NO, REMARK, PERMISSION_NAME, ICON, PERMISSION_TYPE, P_PERMISSION_ID, SYS_ID, SORT_NO, DISPLAY, ALIVE_FLAG, ADD_USER_ID, ADD_TIME, OPR_USER_ID, OPR_TIME, SUBSYS_CODE, CHECK_FLAG) VALUES(3, 'admin/role/mainPage', 'sys:user:list', NULL, '角色管理', '角色管理', NULL, False, 1, NULL, 2, 1, NULL, 1, '2018-05-06 23:33:19', NULL, NULL, 'MENU_USER', NULL);
INSERT INTO sys_permission_config(PERMISSION_CONFIG_ID, PERMISSION_URL, PERMISSION_CONFIG, SEQ_NO, REMARK, PERMISSION_NAME, ICON, PERMISSION_TYPE, P_PERMISSION_ID, SYS_ID, SORT_NO, DISPLAY, ALIVE_FLAG, ADD_USER_ID, ADD_TIME, OPR_USER_ID, OPR_TIME, SUBSYS_CODE, CHECK_FLAG) VALUES(4, 'admin/user/mainPage', 'sys:user:list', NULL, '用户管理', '用户管理', NULL, True, 1, NULL, 3, 1, NULL, 1, '2018-05-06 23:33:53', NULL, NULL, 'MENU_USER', NULL);
INSERT INTO sys_permission_config(PERMISSION_CONFIG_ID, PERMISSION_URL, PERMISSION_CONFIG, SEQ_NO, REMARK, PERMISSION_NAME, ICON, PERMISSION_TYPE, P_PERMISSION_ID, SYS_ID, SORT_NO, DISPLAY, ALIVE_FLAG, ADD_USER_ID, ADD_TIME, OPR_USER_ID, OPR_TIME, SUBSYS_CODE, CHECK_FLAG) VALUES(5, 'admin/sysdatadict/sysDataDictMainPage', 'sys:user:list', NULL, '数据字典', '数据字典', NULL, True, 1, NULL, 4, 1, NULL, 1, '2018-05-06 23:33:53', NULL, NULL, 'MENU_USER', NULL);

INSERT INTO sys_role(ROLE_ID, ROLE_CODE, ROLE_NAME, ALIVE_FLAG, ADD_USER_ID, ADD_TIME, OPR_USER_ID, OPR_TIME, ROLE_TYPE) VALUES(1, 'admin', '系统管理员', 1, NULL, '2018-04-18 17:15:03', 1, '2018-05-08 17:12:07', 2);

INSERT INTO sys_role_permission(ROLE_ID, PERMISSION_ID) VALUES(1, 1);
INSERT INTO sys_role_permission(ROLE_ID, PERMISSION_ID) VALUES(1, 2);
INSERT INTO sys_role_permission(ROLE_ID, PERMISSION_ID) VALUES(1, 3);
INSERT INTO sys_role_permission(ROLE_ID, PERMISSION_ID) VALUES(1, 4);
INSERT INTO sys_role_permission(ROLE_ID, PERMISSION_ID) VALUES(1, 5);

INSERT INTO sys_user(USER_ID, USER_ACCOUNT, USER_PASSWORD, USER_NAME, PHONE, ADD_TIME, LOGIN_TIME, LOGIN_IP, STATUS) VALUES(1, 'admin', 'c4ca4238a0b923820dcc509a6f75849b', '系统管理员', NULL, '2018-01-01 08:00:00', '2018-05-15 12:39:32', '172.18.112.1', 1);

INSERT INTO sys_user_role(USER_ID, ROLE_ID) VALUES(1, 1);
