server:
   port: 11001
   compression:
      enabled: true
   undertow:
      uriEncoding: utf-8
      io-threads: 32
      worker-threads: 32
      buffer-size: 32
      buffers-per-region: 32
      direct-buffers: true
spring:
   application:
      name: register-center
eureka:
   instance:
      lease-expiration-duration-in-seconds: 60
      lease-renewal-interval-in-seconds: 15
      prefer-ip-address: true
      ip-address: 127.0.0.1
   client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
   server:
      enable-self-preservation: true
      disable-delta: false
      sync-when-timestamp-differs: true
      number-of-replication-retries: 10
      peer-node-read-timeout-ms: 30000