elasticsearch: # elasticsearch配置
   host: 192.168.100.213:9200 # 节点地址，使用逗号进行分割
   #authorize: # 访问授权(由于2018年elasticsearch的全球大规模攻击，从这次开始elasticsearch将全部需要授权使用,es7对接时启用)
   #   username: elastic
   #   password: yzh0623
   protocol: http # 网络协议
   common:
      max-connect: 50 # 最大连接数
      max-connect-per-route: 50 # 最大路由连接数
